pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  - script: |
      yarn
    displayName: "Install Dependencies"

  - script: |
      yarn run ci
    displayName: "Run CI"